! GENERATE A RANDOM PERMUTATION VECTOR
! INPUT: NUM, LENGTH OF MYPERM
! OUTPUT: MYPERM, RANDOM PERMUTATION VECTOR

SUBROUTINE RANDPERM(NUM, MYPERM)

	INTEGER, INTENT(IN) :: NUM
	INTEGER, DIMENSION(NUM), INTENT(INOUT) :: MYPERM

	INTEGER :: MYNUMBER, I, J, K
	DOUBLE PRECISION, DIMENSION(NUM) :: RAND2

	CALL RANDOM_NUMBER(RAND2)

	DO I=1,NUM
		MYNUMBER=1
		DO J=1,NUM
			IF (RAND2(I) > RAND2(J)) THEN
				MYNUMBER = MYNUMBER+1
			END IF
		END DO
		DO K=1,I-1
			IF (RAND2(I) <= RAND2(K) .AND. RAND2(I) >= RAND2(K)) THEN
				MYNUMBER = MYNUMBER+1
			END IF
		END DO
		MYPERM(I) = MYNUMBER
	END DO
	RETURN

END SUBROUTINE RANDPERM
